services:
  # Aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soundfy_app
    restart: unless-stopped
    working_dir: /laravel
    volumes:
      - .:/laravel
    networks:
      - soundfy_network
    depends_on:
      - database

  # Servidor web Nginx
  webserver:
    image: nginx:alpine
    container_name: soundfy_webserver
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/laravel
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - soundfy_network
    depends_on:
      - app

  # Base de datos MySQL
  database:
    image: mysql:8.0
    container_name: soundfy_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: soundfy
      MYSQL_ROOT_PASSWORD: secure_password_123
      MYSQL_USER: soundfy_user
      MYSQL_PASSWORD: secure_password_123
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - soundfy_network

# Volúmenes persistentes
volumes:
  dbdata:
    driver: local

# Red personalizada
networks:
  soundfy_network:
    driver: bridge